version: '3.2'
services:
    was:
      image: jetherrodrigues/was_8_5_5:stable
      container_name: was
      ports:
        - "28000:28000"
        - "28001:28001"
      networks: 
        - citi-pss-network
      depends_on: 
        - "oracle"
      volumes: 
        - /opt/citi-dependencies/was:/home
      stdin_open: true
      tty: true
      command: > 
          bash -c "/opt/IBM/WebSphere/AppServer/profiles/Dmgr01/bin/startManager.sh 
          && /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/bin/startNode.sh"
      
    oracle:
      image: alexeiled/docker-oracle-xe-11g:latest
      container_name: oracle-db
      networks: 
          - citi-pss-network
      shm_size: '1gb'
      volumes: 
        - /opt/citi-dependencies/oracle/db:/usr/lib/oracle/xe/oradata/XE
        - /opt/citi-dependencies/oracle/scripts:/etc/entrypoint-initdb.d
      ports:
        - "1521:1521"
        - "8080:8080"
networks: 
    citi-pss-network:
        driver: bridge 