version: '3.2'
services:
    was:
      image: jetherrodrigues/was_8_5_5:stable
      container_name: was
      ports:
        - "28000:28000"
        - "28001:28001"
      networks: 
        - citi-pss-network
      entrypoint: ['bash']
      # environment:
      #   - DEBUG=true
      depends_on: 
        - "oracle"
      volumes: 
        - /opt/citi-dependencies/was:/home      
      tty: true    

    oracle:
      image: alexeiled/docker-oracle-xe-11g:latest
      container_name: oracle-db
      networks: 
          - citi-pss-network
      shm_size: '1gb'
      volumes: 
        - /opt/citi-dependencies/oracle/db:/usr/lib/oracle/xe/oradata/XE
        - /opt/citi-dependencies/oracle/scripts:/etc/entrypoint-initdb.d
      ports:
        - "1521:1521"
        - "8080:8080"
      entrypoint: ['bash']
      tty: true
networks: 
    citi-pss-network:
        driver: bridge 