version: '3.2'
services:
    was:
      #image: jetherrodrigues/was_8_5_5:stable
      image: jetherrodrigues/websphere-traditional:8.5.5.12-install
      container_name: server1
      hostname: server1
      ports:
         - "9080:9080"
         - "9043:9043"
         - "9443:9443"
        #- "28000:28000"
        #- "28001:28001"
        #- "28013:28013"
      networks: 
        - citi-pss-network
      #entrypoint: ['bash']
      #environment:
      #   - DEBUG=true
      depends_on: 
        - "oracle"
      volumes: 
        - /opt/citi-dependencies/was:/home      
      tty: true    

    oracle:
      image: alexeiled/docker-oracle-xe-11g:latest
      container_name: oracle-db
      networks: 
          - citi-pss-network
      shm_size: '1gb'
      volumes: 
        - /opt/citi-dependencies/oracle/db:/usr/lib/oracle/xe/oradata/XE
        - /opt/citi-dependencies/oracle/scripts:/etc/entrypoint-initdb.d
      ports:
        - "1521:1521"
        - "8080:8080"
      #entrypoint: ['bash']
      tty: true
      command: sh start.sh
networks: 
    citi-pss-network:
        driver: bridge 
